POST http://localhost:5000/api/v3/covers HTTP/1.1
content-type: application/json

{
    "name": "Cover de prueba",
    "type": "VIP",
    "price": 20000,
    "date": "01/30/2023",
    "limit": 30,
    "initial_limit": 30,
    "hour":"05:00 PM",
    "description": "Cover realizado en la prueba",
    "image": "",
    "store": "3120273d-0598-4708-9917-c6e03a314967",
    "status": false
}

###

GET http://localhost:5000/api/v3/covers/3120273d-0598-4708-9917-c6e03a314967 HTTP/1.1
content-type: application/json

###

PUT http://localhost:5000/api/v3/covers HTTP/1.1
content-type: application/json

{
    "uuid": "68ab6421-277e-4304-812a-beb7335ea798",
    "data": 
        {
            "uuid": "68ab6421-277e-4304-812a-beb7335ea798",
    "type": "VIP",
    "image": "imagendeprueba.png"
    }
}

###

DELETE   http://localhost:5000/api/v3/covers/0cd995b8-9cc3-4207-acbe-cb32e0b3e7bd



