name: CI/CD Partiaf Monorepo

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [16.x]
      steps:
        - name: Install dependencies
          run: pnpm install && cp .env.example .env
        